// <auto-generated />
using System;
using CourseHouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursesHouse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240311090122_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseHouse.Models.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Author")
                        .HasColumnType("int");

                    b.Property<int?>("CourseViewViewId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ViewTestTestId")
                        .HasColumnType("int");

                    b.HasKey("ContentId");

                    b.HasIndex("Author");

                    b.HasIndex("CourseViewViewId");

                    b.HasIndex("ViewTestTestId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("CourseHouse.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Author")
                        .HasColumnType("int");

                    b.Property<string>("CourseFlow")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("CoursePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PurchasedCourses")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("Author");

                    b.HasIndex("PurchasedCourses");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseComment", b =>
                {
                    b.Property<int>("CourseCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CourseCommentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseComments");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseGrade", b =>
                {
                    b.Property<int>("CourseGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(2,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CourseGradeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseGrades");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseView", b =>
                {
                    b.Property<int>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentOrder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("ViewId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseViews");
                });

            modelBuilder.Entity("CourseHouse.Models.CreditCard", b =>
                {
                    b.Property<int>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CreditCardId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("CourseHouse.Models.LastVisited", b =>
                {
                    b.Property<int>("LastVisitedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LastVisitedCourses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastVisitedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LastVisitedId");

                    b.ToTable("LastVisited");
                });

            modelBuilder.Entity("CourseHouse.Models.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Author")
                        .HasColumnType("int");

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CourseViewViewId")
                        .HasColumnType("int");

                    b.Property<int?>("ViewTestTestId")
                        .HasColumnType("int");

                    b.HasKey("PictureId");

                    b.HasIndex("Author");

                    b.HasIndex("CourseViewViewId");

                    b.HasIndex("ViewTestTestId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("CourseHouse.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalSpend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CourseHouse.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CourseHouse.Models.TestAnswer", b =>
                {
                    b.Property<int>("TestAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ViewTestId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("correct")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TestAnswerId");

                    b.HasIndex("ViewTestId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("CourseHouse.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseHouse.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Author")
                        .HasColumnType("int");

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CourseViewViewId")
                        .HasColumnType("int");

                    b.Property<int?>("ViewTestTestId")
                        .HasColumnType("int");

                    b.HasKey("VideoId");

                    b.HasIndex("Author");

                    b.HasIndex("CourseViewViewId");

                    b.HasIndex("ViewTestTestId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("CourseHouse.Models.ViewTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentOrder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("CourseId");

                    b.ToTable("ViewTests");
                });

            modelBuilder.Entity("CourseHouse.Models.Content", b =>
                {
                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.CourseView", null)
                        .WithMany("Content")
                        .HasForeignKey("CourseViewViewId");

                    b.HasOne("CourseHouse.Models.ViewTest", null)
                        .WithMany("Content")
                        .HasForeignKey("ViewTestTestId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.Course", b =>
                {
                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.Purchase", null)
                        .WithMany("PurachasedCourses")
                        .HasForeignKey("PurchasedCourses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseComment", b =>
                {
                    b.HasOne("CourseHouse.Models.Course", "Course")
                        .WithMany("Comments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseGrade", b =>
                {
                    b.HasOne("CourseHouse.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseView", b =>
                {
                    b.HasOne("CourseHouse.Models.Course", "Course")
                        .WithMany("CourseViews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseHouse.Models.Picture", b =>
                {
                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.CourseView", null)
                        .WithMany("Pictures")
                        .HasForeignKey("CourseViewViewId");

                    b.HasOne("CourseHouse.Models.ViewTest", null)
                        .WithMany("Pictures")
                        .HasForeignKey("ViewTestTestId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.Purchase", b =>
                {
                    b.HasOne("CourseHouse.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.TestAnswer", b =>
                {
                    b.HasOne("CourseHouse.Models.ViewTest", "ViewTest")
                        .WithMany("TestAnswers")
                        .HasForeignKey("ViewTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViewTest");
                });

            modelBuilder.Entity("CourseHouse.Models.User", b =>
                {
                    b.HasOne("CourseHouse.Models.Course", null)
                        .WithMany("EnrolledUsers")
                        .HasForeignKey("CourseId");

                    b.HasOne("CourseHouse.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CourseHouse.Models.Video", b =>
                {
                    b.HasOne("CourseHouse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHouse.Models.CourseView", null)
                        .WithMany("Videos")
                        .HasForeignKey("CourseViewViewId");

                    b.HasOne("CourseHouse.Models.ViewTest", null)
                        .WithMany("Videos")
                        .HasForeignKey("ViewTestTestId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseHouse.Models.ViewTest", b =>
                {
                    b.HasOne("CourseHouse.Models.Course", "Course")
                        .WithMany("ViewsTests")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseHouse.Models.Course", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CourseViews");

                    b.Navigation("EnrolledUsers");

                    b.Navigation("ViewsTests");
                });

            modelBuilder.Entity("CourseHouse.Models.CourseView", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("Pictures");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("CourseHouse.Models.Purchase", b =>
                {
                    b.Navigation("PurachasedCourses");
                });

            modelBuilder.Entity("CourseHouse.Models.ViewTest", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("Pictures");

                    b.Navigation("TestAnswers");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
